Add import/export rake task for ConfigReport
theforeman/foreman_host_reports pull request #32
Opened 2022-03-11 10:41 UTC by avitova

2022-03-14 08:35 UTC, lzap commented on lib/tasks/export.rake
> +namespace :reports do
Please rename to host_reports.

2022-03-14 08:49 UTC, lzap commented on lib/tasks/import.rake
> +      end
This is a bit slow, try to wrap it into a single transaction:

    Log.transaction do ... end

2022-03-14 08:55 UTC, lzap commented on lib/tasks/import.rake
> +namespace :reports do
Please add rake comment, something like "This task is only for development purposes, database tables must be clean before importing."

2022-03-14 08:55 UTC, lzap commented on lib/tasks/export.rake
> +  task :export => :environment do
Please add rake comment, something like "Export all reports as CSV files. This task is only for development purposes."

2022-03-14 08:56 UTC, lzap commented on lib/tasks/import.rake
> +    end
At the end of each file, plese set PG sequence to the highest seen ID + 1: https://www.postgresql.org/docs/9.1/sql-altersequence.html

2022-03-17 15:44 UTC, avitova commented
Alter sequence does not allow subqueries, but this should work the same.

2022-03-18 09:24 UTC, lzap commented on lib/tasks/import.rake
> +      end
You need to wrap the whole loop in a transaction, that should speed things up.

The same for sources, messages, reports.

2022-03-18 09:25 UTC, lzap commented on lib/tasks/import.rake
> +    ActiveRecord::Base.connection.exec_query("SELECT setval('reports_id_seq', (SELECT MAX(id) + 1 FROM reports), false)")
Great, now please do this for all the tables.

2022-03-25 12:38 UTC, lzap requested changes
Other than that, works great as long as the database is cleaned up prior import:

```
[lzap@nuc foreman]$ psql foreman-dev
psql (13.4)
Pro získání nápovědy napište "help".

foreman-dev=# truncate logs, messages, sources, reports;
```

2022-03-25 12:38 UTC, lzap commented on lib/tasks/export.rake
> +namespace :foreman_host_reports do
Can you rename this to just `host_reports` to match the existing namespace?

2022-03-25 12:38 UTC, lzap commented on lib/tasks/import.rake
> +namespace :foreman_host_reports do
Can you rename this to just `host_reports` to match the existing namespace?

2022-03-25 15:15 UTC, avitova commented
Sure, fixed.

2022-04-08 05:36 UTC, lzap commented
Thanks for the code, I am closing as we want to re-focus on other things.

2022-04-08 05:36 UTC, closed without merging